version: "3.8"
services: 
  nest_api_test:  
    image: nest_auth
    build:
     dockerfile: Dockerfile
     context: .
     target: development
    ports:
      - 3333:3333
    command: npm run start:migrate:test
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
     - nestjs-network

  postgres:
    image: postgres:13
    env_file:
      - docker.env     
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
     - nestjs-network  
volumes:
  db_data:
networks:
  nestjs-network:     