version: "3.8"
services:
  nginx:
   image: nginx:stable-alpine
   volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
   ports:
   - 80:80
   networks:
    - nestjs-network

  nest_api:
    image: srdjankljajo/nest_api  
    deploy:
     replicas: 2
     restart_policy:
      condition: any
     update_config:
      parallelism: 2
      delay: 15s 
    build:
     context: .
    ports:
      - 3333:80 
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
     - nestjs-network